name: fingerprintjs_example
description: Fingerprintjs example.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fingerprintjs:
    path: ../

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
