name: fingerprintjs
version: 1.0.4
description: Fingerprintjs wrapper for Dart - A modern & flexible browser fingerprinting library
repository: https://github.com/samihaddad/dart-fingerprintjs
issue_tracker: https://github.com/samihaddad/dart-fingerprintjs/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3

dev_dependencies:
  build_runner: ^1.2.0
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.2
